### ISSUE TITLE
Instructor reports blank

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1367]
They are blank, despite the fact the data is there, for a valid student who used the link...

[unit5-data.txt](https://github.com/memphis-iis/mofacts/files/13923890/unit5-data.txt)

![Downloads 1_12_2024 2_41_10 PM](https://github.com/memphis-iis/mofacts/assets/13023147/0bec57cf-16ff-4a54-aea0-926918039db9)

**Comment by imrryr** [comment]
@MegaGeese still blank on production for my existing class.

**Comment by JRustyHaner** [comment]
@imrryr after looking at the office 365 login and the database on the production server:

-The section user map is not populated. Mofacts doesn't know what student belongs to what class
-All your students were using their memphis accounts? If so, I investigated the office 365 login and the function signInNotify wasn;'t there, which writes the user to the section map collection.

If this is where the bug is (I think it is), I'm testing a PR right now and will post it for review.
