### ISSUE TITLE
CogniVideo Experiment Video Page bugs

### ISSUE THREAD

**Issue by shelbik37** [memphis-iis/mofacts#1421]
1. There is no "Continue" button on the video pages. So, once I get through the first video, I can't continue onto any of the next pages/videos. 
2. At the bottom of the video player pages, it says "NaN seconds until the next question." Do we think we can get rid of/change this? If not, then it's not a huge deal to leave it.

**Comment by JRustyHaner** [comment]
@shelbik37 your tdf has no question times in it, so it returns the time difference is 0. I'm going to split that into a different issue.

**Comment by imrryr** [comment]
@JRustyHaner I would imagine that the message should not pop up when there are no questions. Also, I think Shelbi is saying there is no continue button at all even after it finishes. She says she can't continue "once I get through the first video"

**Comment by MegaGeese** [comment]
It seems i forgot to add an 'onEnd' event to continue to the next unit.

**Comment by JRustyHaner** [comment]
@imrryr These were two seperate issues.  UISettings takes care of the progress bar appearing at all, but should she want it, we do not want it to say NaN seconds until next event.

**Comment by imrryr** [comment]
@JRustyHaner the progress bars are not currently being used by anyone. Since a video shows progress, they seem redundant here, simply seem to add an unneeded support task for you

**Comment by imrryr** [comment]
@JRustyHaner part of the problem is that UIsettings is getting totally unmanageable. Please help with documentation if you can https://github.com/memphis-iis/mofacts/wiki/Content-Creation-and-Posting

I'm having trouble finding all the details spread across dozens of issues, and things have changed significantly during this process.

**Comment by imrryr** [comment]
> @imrryr These were two seperate issues. UISettings takes care of the progress bar appearing at all, but should she want it, we do not want it to say NaN seconds until next event.

@JRustyHaner so, but the key point is that we need to find out if the feature is wanted in all cases like this, not assume it is wanted... Unused features are costly on many levels

**Comment by JRustyHaner** [comment]
@imrryr It was a feature that was already implemented.

**Comment by JRustyHaner** [comment]
@imrryr @shelbik37 She specifically requested this in one of our meetings about two months ago, and if the defaults need to be changed then that's okay, but that isn't what the issue was written to convey. The previous defaults from mofacts were for a bar/text to be displayed. If we want this feature for videos, then we need it to not display NaN.

**Comment by imrryr** [comment]
@OK, well, if it is in some other issue no wonder I am wrong
