### ISSUE TITLE
Problems with MC question recording

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1432]
Skip recorded for incorrect instead of actual input (skip is not recorded, it is in the tdf...)

A double record at the same time for A_5, only one can be correct..0 but also for these trials--
incorrect feedback length
Example file for a quiz on production.

[unit25-data.xlsx](https://github.com/memphis-iis/mofacts/files/14668824/unit25-data.xlsx)
[unit25.zip](https://github.com/memphis-iis/mofacts/files/14668830/unit25.zip)

**Comment by MegaGeese** [comment]
It looks like any time the study is skipped it records the user input as [skip]. I think it may also be recording both of the A_5 stims because of this. 
Basically first user would answer a question incorrect and that would get recorded.
Then user would skip the study which would also get recorded as a new history item.
