### ISSUE TITLE
Remap API Calls to internal network ports

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts#1473]
It said it would email the file to me, but then nothing, and it was only 4 paragraphs to process.

**Comment by JRustyHaner** [comment]
@imrryr the email system will work on next build. We're going to have to keep a running tab on errors with content generation testing, since it hasn't been used in docker before. I expect some hiccups along the way since I can't test this in my development environment (My desktop does not have enough memory available to run all of Andrew's software).

**Comment by JRustyHaner** [comment]
@imrryr I'm changing this to fix the port remapping issues for content generation
