### ISSUE TITLE
Notify user they're starting the last unit

### ISSUE THREAD

**Issue by shelbik37** [memphis-iis/mofacts#1487]
**Describe the bug**
When participants progress through the very last video page, they are unable to return back to the videos. I would like to keep this functionality but am wondering if we can add in video pages (e.g., Page 1 of 4) and a final message on the last video (e.g., This is the last video, do not progress unless finished with this lesson) so that participants do not progress until they are completely done. 

What I'm not sure is if this should be something we spec in the TDF or we could make it a permanent feature. If it's possible and makes sense to make it permanent, that is the route I would like to take.

**Comment by imrryr** [comment]
We could set this in the setspec I think, since it controls the entire tdf. Something that prevents the last unit from ending or offering a next unit option. Soemthing like "allowtdfcompletion" and have it default to TRUE

**Comment by MegaGeese** [comment]
The only road bump I see with this issue is if in the case of adaptive learning their may be no way to know what the last unit actually is, so we either end up alerting the user multiple times that they're on the last unit or we have multiple units created after the last TDF defined unit during the last TDF defined unit.
